repos:

  # STANDARD HOOKS #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  # LINTER & CODE FORMATTER #
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
      - id: ruff-format

  # TYPE CHECKER #
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.0'
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies: [types-requests]
