version: "3"
services:
  app:
    image: music_bot:local
    container_name: musicbot
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: ["python3", "/app/app/main.py"]
    volumes: 
    - ./logs:/app/logs
    - ./app:/app/app
    env_file:
      - .env
    ports:
      - "5678:5678"
