version: "3"
services:
  app:
    image: music_bot:dev
    container_name: musicbot
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: ["python3", "app/main.py"]
    env_file:
      - .env
    ports:
      - "5678:5678"
