services:
  app:
    image: websoftdevs/musicbot:prod
    container_name: musicbot
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: ["python3", "app/main.py"]
    env_file:
      - .env
    ports:
      - "5678:5678"
