version: "3"
services:
  app:
    image: music_bot:local
    container_name: musicbot
    build:
      context: .
      dockerfile: compose/dev/Dockerfile
    volumes:
      - ./app:/app/app
    command: ["python3", "app/app/main.py"]
    env_file:
      - .env
    ports:
      - "5678:5678"
